# Linear Algebra

In this notes, we will discuss vector, matrix, matrix multiplication, inverse matrix, transpose, norm, linear system, and least-square problem.

In [1]:
import numpy as np

## matrix, vector and multiplication

In [2]:
# matrix, vector and multiplication
A = np.array([[1,2,1],[0,1,0]])
x = np.array([[1],[2],[3]])
A@x

array([[8],
       [2]])

In [3]:
# matrix by matrix
B = np.array([[1,0],[0,1],[1,1]])
A@B

array([[2, 3],
       [0, 1]])

## Inverse and transpose

In [4]:
# inverse of a matrix
A = np.array([[1,2],[2,5]])
A_inv = np.linalg.inv(A)
print(np.allclose(A@A_inv, np.identity(2)))
print(np.allclose(A_inv@A, np.identity(2)))

True
True


In [5]:
# not all matrix are invertibe
A = np.array([[1,2],[2,4]])
np.linalg.inv(A)

LinAlgError: Singular matrix

In [6]:
# transpose
A = np.array([[1,2],[2,4]])
print(A)
print(" ")
print(A.T)

[[1 2]
 [2 4]]
 
[[1 2]
 [2 4]]


## Norm 

Mathematical formulas are given during the lecture. You can also check this [page](https://en.wikipedia.org/wiki/Norm_(mathematics)).

In [7]:
# vector norm
x = np.array([1,-1,2,3,-4])
print('For vector x,')
print('L2 norm is ', np.linalg.norm(x))
print('L1 norm is ', np.linalg.norm(x,1))
print('L_infty norm is ',np.linalg.norm(x,np.inf))
print('L4 norm is ', np.linalg.norm(x,4))
print('')

For vector x,
L2 norm is  5.5677643628300215
L1 norm is  11.0
L_infty norm is  4.0
L4 norm is  4.340673182977126

For matrix A,
Frobenius norm is  3.7416573867739413
L2 norm is  3.702459173643833


We can use the same command to compute matrix norm, see examples below.

In [ ]:
# matrix norm 
A = np.arange(4).reshape(2,2)
print('For matrix A,')
print('Frobenius norm is ', np.linalg.norm(A))
print('L2 norm is ', np.linalg.norm(A,2))

## Linear system

We will discuss solving linear system and least square problem.

In many applications, we need to solve a linear system $Ax=b$. The goal is to find $x$ given matrix $A$ and output $b$. If $A$ is a square matrix and invertible, then we can solve the problem by multiplying $A^{-1}$ for both sides. However, computing $A^{-1}$ is expensive. In python, we can use numpy.linalg.solve command to solve $Ax=b$.

In [8]:
A = np.array([[1,2],[2,5]])
b = np.array([[3],[7]])

# solve by using inverse
x_inv = np.linalg.inv(A)@b

# use solve command
x_solve = np.linalg.solve(A,b)

# compare
np.allclose(x_inv,x_solve)

True

Can we solve linear system $Ax=b$ when $A$ is not a square matrix or $A$ is a square matrix but not invertible?

## Least-square problem

We want to find $x$ such that $Ax$ is as close to $b$ as possible, i.e.

$$ \mathop{ \mathrm{min} }_x \|Ax-b\|_2 $$

- if we minimize L2 norm ($\|x\|_2$), it has a nice formula $x = (A^TA)^{-1}A^Tb$. This nice formula comes form normal equation $A^TAx = A^Tb$, which can be obtained by finding the gradient of objective function and setting it to zero.

Minimize L2 norm problem is also called least square problem. Linear regression can be written in this form. Actually, many problems can be written as least square problem.

We can also minimize other norms, but we do not have nice formula. But we can design other algorithms to solve it. 


In [9]:
# verification:
A = np.array([[1,1],[2,2],[1,0]])
b = np.array([[5],[10],[7]])

# inverse matrix
x1 = np.linalg.inv(A.T@A)@A.T@b

# solve command
x2 = np.linalg.solve(A.T@A, A.T@b)

# compare
np.allclose(x1,x2)

True