# Linear Algebra

In this notes, we will discuss vector, matrix, matrix multiplication, inverse matrix, transpose, norm, linear system, and least-square problem.

In [48]:
import numpy as np

## matrix, vector and multiplication

In [4]:
# matrix, vector and multiplication
A = np.array([[1,2,1],[0,1,0]])
x = np.array([[1],[2],[3]])
b = A@x
b.shape

(2, 1)

In [5]:
A = np.array([[1,2,1],[0,1,0]])
x = np.array([1,2,3])
b = A@x
b.shape

(2,)

In [6]:
b

array([8, 2])

In [7]:
# matrix by matrix
B = np.array([[1,0],[0,1],[1,1]])
A@B

array([[2, 3],
       [0, 1]])

## Inverse and transpose

In [9]:
# inverse of a matrix
A = np.array([[1,2],[2,5]])
A_inv = np.linalg.inv(A)
print(np.allclose(A@A_inv, np.identity(2)))
print(np.allclose(A_inv@A, np.identity(2)))

True
True


In [10]:
# not all matrix are invertibe
A = np.array([[1,2],[2,4]])
np.linalg.inv(A)

LinAlgError: Singular matrix

In [12]:
# transpose
A = np.array([[1,10],[2,4]])
print(A)
print(" ")
print(A.T)
print(np.transpose(A))

[[ 1 10]
 [ 2  4]]
 
[[ 1  2]
 [10  4]]
[[ 1  2]
 [10  4]]


## Norm 

Mathematical formulas are given during the lecture. You can also check this [page](https://en.wikipedia.org/wiki/Norm_(mathematics)).

In [13]:
# vector norm
x = np.array([1,-1,2,3,-4])
print('For vector x,')
print('L2 norm is ', np.linalg.norm(x))
#print('L1 norm is ', np.linalg.norm(x,1))
#print('L_infty norm is ',np.linalg.norm(x,np.inf))
#print('L4 norm is ', np.linalg.norm(x,4))
print('')

For vector x,
L2 norm is  5.5677643628300215



In [14]:
x1 = x.reshape(5,1)
x2 = x.reshape(1,5)

print(np.linalg.norm(x1))
print(np.linalg.norm(x2))

5.5677643628300215
5.5677643628300215


We can use the same command to compute matrix norm, see examples below.

In [ ]:
# matrix norm 
A = np.arange(4).reshape(2,2)
print('For matrix A,')
print('Frobenius norm is ', np.linalg.norm(A))
print('L2 norm is ', np.linalg.norm(A,2))

In [16]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [19]:
np.mean(A), np.mean(A, axis=0), np.mean(A, axis=1)

(1.5, array([1., 2.]), array([0.5, 2.5]))

In [21]:
np.linalg.norm(A), np.linalg.norm(A, axis=0), np.linalg.norm(A, axis=1)

(3.7416573867739413,
 array([2.        , 3.16227766]),
 array([1.        , 3.60555128]))

## Linear system

We will discuss solving linear system and least square problem.

In many applications, we need to solve a linear system $Ax=b$. The goal is to find $x$ given matrix $A$ and output $b$. If $A$ is a square matrix and invertible, then we can solve the problem by multiplying $A^{-1}$ for both sides. However, computing $A^{-1}$ is expensive. In python, we can use numpy.linalg.solve command to solve $Ax=b$.

In [53]:
A = np.array([[1,2],[2,5]])
b = np.array([[3],[7]])

# solve by using inverse
x_inv = np.linalg.inv(A)@b

# use solve command
x_solve = np.linalg.solve(A,b)

# compare
np.allclose(x_inv,x_solve)

True

Can we solve linear system $Ax=b$ when $A$ is not a square matrix or $A$ is a square matrix but not invertible?

## Least-square problem

We want to find $x$ such that $Ax$ is as close to $b$ as possible, i.e.

$$ \mathop{ \mathrm{min} }_x \|Ax-b\|^2_2 $$

- if we minimize L2 norm, it has a nice formula $x = (A^TA)^{-1}A^Tb$. This nice formula comes form normal equation $A^TAx = A^Tb$, which can be obtained by finding the gradient of objective function and setting it to zero.

Minimize L2 norm problem is also called least square problem. Linear regression can be written in this form. Actually, many problems can be written as least square problem.

We can also minimize other norms, but we do not have nice formula. But we can design other algorithms to solve it. 


In [50]:
# verification:
A = np.array([[1,1],[2,2],[1,0]])
b = np.array([[5],[10],[7]])

# inverse matrix
x1 = np.linalg.inv(A.T@A)@A.T@b

# solve command
x2 = np.linalg.solve(A.T@A, A.T@b)

# compare
np.allclose(x1,x2)

True

## Your own linear system solver

Suppose you are working for a math software company and they ask you to design a software for solving linear systems. 

It is better to do it using class. Here is an example. 

P.S. The class is far from complete because the docstrings are missing. Could you please add it here?

In [68]:
class LinearSolver():
    
    
    def __init__(self, A, b):
        
        self.A = A
        self.b = b
        
        self.A_shape = A.shape
        self.b_shape = b.shape
        
        self.sol = None
        
        if np.ndim(self.A) == 2:
            
            print('Initialization is done!!!!!!!!!!')
            
        else:
            
            print(f'Only 2d numpy array is accepted. Now the dimension of A is {np.ndim(self.A)}')
        
    def check_shape(self):
        
        if self.A_shape[0] == self.b_shape[0]:
            
            print('Shape check passed.')
            
            
            if self.A_shape[0] == self.A_shape[1]:
                
                print('Square matrix. Recommend solve equation.')
                
            if self.A_shape[0] < self.A_shape[1]:
                
                print('Number of rows is smaller than number of columns. LeastNorm is recommended.')
                
            if self.A_shape[0] > self.A_shape[1]:
                
                print('Number of rows is larger than number of columns. LeastSquare is recommended.')
                     
        else:
            
            print('Shape check fails.')
            
        
    def solve(self, solver="equation"):
        
        if solver == "equation":
            
            return np.linalg.solve(self.A, self.b)
        
        if solver == "LeastSquare":
            
            return np.linalg.solve(self.A.T@self.A, self.A.T@self.b)
        
    def linear_equation(self, solver="solve"):
        
        if solver == "solve":
            
            self.sol = np.linalg.solve(self.A, self.b)
            
            return self.sol
        
        if solver == "inverse":
            
            self.sol = np.linalg.inv(self.A) @ self.b
            
            return self.sol
        
    def LeastSquare(self):
        
        self.sol = np.linalg.solve(self.A.T@self.A, self.A.T@self.b)
        
        return self.sol
    
    def Leastnorm(self):
        
        self.sol = self.A.T @ np.linalg.inv(self.A@self.A.T) @ self.b
        
        return self.sol
    
    def norm(self):
        
        if self.sol == None:
            
            print("Solution vector is not computed. Norm is not available.")
            
        else:
            
            return np.linalg.norm(self.sol)

Checking the correctness of your code can be done by running test examples. Given the following test examples, could you please write down the desired output without running them?

In [71]:
# Test example:

A = np.array([[1,2],[2,5]]).reshape(1,2,2,1)
b = np.array([[3],[7]])
linear = LinearSolver(A,b)

Initialization is done!!!!!!!!!!


In [ ]:
# Test example:

A = np.array([[1,2],[2,4]])
b = np.array([[3],[7]])
linear = LinearSolver(A,b)

In [ ]:
# Test example:

A = np.array([[1,2],[2,5]])
b = np.array([[3],[7]])
linear = LinearSolver(A,b)
linear.solve()

In [ ]:
# Test example:

A = np.array([[1,1],[2,2],[1,0]])
b = np.array([[5],[10],[7]])
linear = LinearSolver(A,b)
linear.LeastSquare()

In [ ]:
# Test example:

A = np.array([[1,1],[2,2],[1,0],[10,20],[5,7],[3,0]])
b = np.array([[5],[10],[7]])
linear = LinearSolver(A,b)
linear.check_shape()